import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { AI } from './action';

const inter = Inter({ subsets: ['latin'] });
const AIProvider = AI as unknown as any;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-full max-h-screen">
        <div className="w-full h-full max-h-screen flex flex-col">
          <Header />
          <div className="flex-1">
            <AIProvider>{children}</AIProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
